steps:
  - name: tag-release
    when:
      - branch: main
        event: push
    image: git.ste.haus/infrastructure/cicd-builder:latest
    pull: true
    environment:
      CICD_KEY:
        from_secret: CICD_KEY
    commands:
      - set-output VERSION $(tag-release)

  - name: build-and-push
    when:
      - branch: main
        event: push
    image: docker:dind
    environment:
      CICD_USERNAME:
        from_secret: CICD_USERNAME
      CICD_PASSWORD:
        from_secret: CICD_PASSWORD
    commands:
      - source .step_outputs
      - docker login git.ste.haus --username $CICD_USERNAME --password $CICD_PASSWORD
      - docker build -t git.ste.haus/$CI_REPO:$STEP_OUTPUT_VERSION -t git.ste.haus/$CI_REPO:latest .
      - docker push git.ste.haus/$CI_REPO:$STEP_OUTPUT_VERSION
      - docker push git.ste.haus/$CI_REPO:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
